"""initial_schema

Revision ID: 21232ece52e3
Revises: 
Create Date: 2026-05-02 12:11:26.371872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21232ece52e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_days_per_year', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'hr_officer', 'payroll_officer', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employmenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employee_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payruns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'finalized', 'paid', name='payrunstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'on_leave', 'holiday', 'weekend', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_employee_date')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_balance_employee_type_year')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leaverequeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payrun_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('leave_days', sa.Integer(), nullable=False),
    sa.Column('lop_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generated', 'sent', name='payslipstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pf_employer_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structures')
    op.drop_table('payslips')
    op.drop_table('leave_requests')
    op.drop_table('leave_balances')
    op.drop_table('attendance_logs')
    op.drop_table('payruns')
    op.drop_table('employee_profiles')
    op.drop_table('users')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
