"""Add department and profile fields

Revision ID: 3c0518b0d708
Revises: b7e23cc10245
Create Date: 2026-05-03 05:07:23.753065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0518b0d708'
down_revision: Union[str, None] = 'b7e23cc10245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import uuid
from sqlalchemy.orm import Session

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('employee_profiles', sa.Column('department_id', sa.String(length=36), nullable=True))
    op.add_column('employee_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('residing_address', sa.String(length=500), nullable=True))
    op.add_column('employee_profiles', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('employee_profiles', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('employee_profiles', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('employee_profiles', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('employee_profiles', sa.Column('uan_number', sa.String(length=20), nullable=True))
    op.add_column('employee_profiles', sa.Column('bank_details', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'employee_profiles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    # Custom Data Migration
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # 1. Fetch unique departments from existing data
    result = bind.execute(sa.text("SELECT DISTINCT department FROM employee_profiles WHERE department IS NOT NULL AND department != ''"))
    existing_departments = [row[0] for row in result]
    
    dept_map = {}
    for dept_name in existing_departments:
        dept_id = str(uuid.uuid4())
        dept_map[dept_name] = dept_id
        # Insert into departments
        bind.execute(sa.text("INSERT INTO departments (id, name) VALUES (:id, :name)"), {"id": dept_id, "name": dept_name})
        
    # 2. Update employee profiles with new department_id
    for dept_name, dept_id in dept_map.items():
        bind.execute(
            sa.text("UPDATE employee_profiles SET department_id = :dept_id WHERE department = :dept_name"),
            {"dept_id": dept_id, "dept_name": dept_name}
        )
        
    op.drop_column('employee_profiles', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_profiles', type_='foreignkey')
    op.drop_column('employee_profiles', 'bank_details')
    op.drop_column('employee_profiles', 'uan_number')
    op.drop_column('employee_profiles', 'pan_number')
    op.drop_column('employee_profiles', 'marital_status')
    op.drop_column('employee_profiles', 'gender')
    op.drop_column('employee_profiles', 'personal_email')
    op.drop_column('employee_profiles', 'nationality')
    op.drop_column('employee_profiles', 'residing_address')
    op.drop_column('employee_profiles', 'date_of_birth')
    op.drop_column('employee_profiles', 'department_id')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
