"""add_permissions_table

Revision ID: f6d2c30afe47
Revises: c3d4e5f6a1b2
Create Date: 2026-05-02 23:57:37.200005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d2c30afe47'
down_revision: Union[str, None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_employee_code'), 'employee_profiles', type_='unique')
    op.drop_index(op.f('ix_employee_profiles_employee_code'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_employee_code'), 'employee_profiles', ['employee_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_profiles_employee_code'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_employee_code'), 'employee_profiles', ['employee_code'], unique=False)
    op.create_unique_constraint(op.f('uq_employee_code'), 'employee_profiles', ['employee_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
